-- MySQL Script generated by MySQL Workbench
-- Mon Sep  3 13:06:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veraplan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veraplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veraplan` DEFAULT CHARACTER SET utf8 ;
USE `veraplan` ;

-- -----------------------------------------------------
-- Table `veraplan`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veraplan`.`User` (
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `veraplan`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `veraplan`;
INSERT INTO `veraplan`.`User` (`email`, `password`, `name`, `surname`) VALUES ('test@test.com', 'password', 'john', 'brown');
INSERT INTO `veraplan`.`User` (`email`, `password`, `name`, `surname`) VALUES ('blub@blub.com', 'derp', 'bobby', 'fisher');

COMMIT;

